### ISSUE TITLE
Packaging?

### ISSUE THREAD

**Issue by jkahn** [wpm/tf_model_session#1]
Want to consider using [cookiecutter-pylibrary](https://github.com/ionelmc/cookiecutter-pylibrary) to package this?  (That's a heavyweight package, but you get hooks for writing tests and CI code.)

Also, it will give you a setup.py with things like dependency management and the tools to (maybe) upload to pypi (and/or Anaconda).

**Comment by wpm** [comment]
I think packaging is overkill for this. It's mostly an educational example, not worth a slot in the pip namespace. I imagine anyone wanting to use the code would just copy-paste `model_session.py`.

Maybe ultimately I should contribute this back to the TensorFlow project.
